### ISSUE TITLE
Institution (authenticated) Items are not displayed on Collection Items Page to logged in users.

### ISSUE THREAD

**Issue by kdid** [nulib/elastic-proxy#1]
### Description

When NetID users are signed in they should see items that have visibility that is "Institution" (authenticated). When you view a detail page for a collection (For example: http://dc.stack.rdc-staging.library.northwestern.edu/collections/854086ad-0cba-4d59-acd0-5d81a69c19a2) you are shown only items that are Public (open) even if you are logged in. 

The associated query is here:
https://github.com/nulib/next-gen-front-end-react/blob/deploy/staging/src/api/elasticsearch-api.js#L62

### Done Looks Like 
- [ ] collection detail page shows Institution items to logged in users

**Comment by davidschober** [comment]
Closing this. I believe this was fixed a while back. If I'm missing something, let me know.
